using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BullseyeDesktopApp
{
    public partial class AddEditUser : Form
    {
        private bool add;
        const string txtMessage = "Automatically Generated";

        public AddEditUser(bool add)
        {
            InitializeComponent();
            this.add = add;
            PopulateLabels();
        }

        private void AddEditUser_Load(object sender, EventArgs e)
        {
            this.Text = add ? "Bullseye IMS - Add New Employee" : "Bullseye IMS - Edit Employee";
            
            //Disabled autogenerated fields if ADD
            txtID.Enabled = !add;
            txtEmail.Enabled = !add;
            txtUsername.Enabled = !add;
            txtPassword.Enabled = !add;

            // Populates message to txts
            if (add)
            {
                txtID.Text = "Auto Generated";
                txtEmail.Text = txtMessage;
                txtUsername.Text = txtMessage;
                txtPassword.Text = txtMessage;
            }
        }


        //           POPULATE LABELS
        //
        // Populates labels with user data from static class
        private void PopulateLabels()
        {
            lblUser.Text = StaticHelpers.UserSession.CurrentUser?.Username ?? ""; //If null empty string
            lblUser.ForeColor = Color.Red;

            lblLocation.Text = StaticHelpers.UserSession.UserLocation ?? "";
            lblLocation.ForeColor = Color.Red;

        }
    }
}
